// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2

package com.iti.model.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="cart"
    ,catalog="naseejstore"
)
public class Cart  implements java.io.Serializable {


     private CartId id;
     private UserDetails userDetails;
     private Product product;
     private Integer quantity;
    private CartId id;
    private Product product;
    private UserDetails userDetails;
    private Integer quantity;

    public Cart() {
    }

	
    public Cart(CartId id, UserDetails userdetails, Product product) {

    public Cart(CartId id, Product product, UserDetails userDetails) {
        this.id = id;
        this.userDetails = userdetails;
        this.product = product;
        this.product = product;
        this.userDetails = userDetails;
    }
    public Cart(CartId id, UserDetails userdetails, Product product, Integer quantity) {
       this.id = id;
       this.userDetails = userdetails;
       this.product = product;
       this.quantity = quantity;
    public Cart(CartId id, Product product, UserDetails userDetails, Integer quantity) {
        this.id = id;
        this.product = product;
        this.userDetails = userDetails;
        this.quantity = quantity;
    }

    @EmbeddedId


    @AttributeOverrides( {
            @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ),
            @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public CartId getId() {
        return this.id;
    }

    public void setId(CartId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public UserDetails getUserDetails() {
        return this.userDetails;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProducts() {
        return this.product;
    }

    public void setProducts(Product product) {
        this.product = product;
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }


    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


