// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2
package com.iti.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Colors generated by hbm2java
 */
@Entity
@Table(name="colors"
    ,catalog="naseejstore"
)
public class Colors  implements java.io.Serializable {


     private String colorName;

    public Colors() {
    }

    public Colors(String colorName) {
       this.colorName = colorName;
    }
   
     @Id 

    
    @Column(name="color_name", unique=true, nullable=false, length=45)
    public String getColorName() {
        return this.colorName;
    }
    
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }




}


