// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2
package com.iti.model.entity;


import javax.persistence.*;

/**
 * Interests generated by hbm2java
 */
@Entity
@Table(name = "interests"
        , catalog = "naseejstore"
)
public class Interest implements java.io.Serializable {


    private String interest;
    private UserDetails userDetails;

    public Interest() {
    }

    public Interest(String interest) {
        this.interest = interest;
    }

    @Id
    public String getInterest() {
        return interest;
    }

    public void setInterest(String interest) {
        this.interest = interest;
    }

    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public UserDetails getUserDetails() {
        return this.userDetails;
    }

    public void setUserDetails(UserDetails userdetails) {
        this.userDetails = userdetails;
    }


    @Override
    public String toString() {
        return "Interest{" +
                "interest='" + interest + '\'' +
                '}';
    }
}


