// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2
package com.iti.model.entity;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdersHasProducts generated by hbm2java
 */
@Entity
@Table(name="orders_has_products"
    ,catalog="naseejstore"
)
public class OrdersHasProducts  implements java.io.Serializable {


     private OrdersHasProductsId id;
     private Products products;
     private Orders orders;
     private int quantity;

    public OrdersHasProducts() {
    }

    public OrdersHasProducts(OrdersHasProductsId id, Products products, Orders orders, int quantity) {
       this.id = id;
       this.products = products;
       this.orders = orders;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ordersOrderId", column=@Column(name="orders_order_id", nullable=false) ), 
        @AttributeOverride(name="productsProductId", column=@Column(name="products_product_id", nullable=false) ) } )
    public OrdersHasProductsId getId() {
        return this.id;
    }
    
    public void setId(OrdersHasProductsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="products_product_id", nullable=false, insertable=false, updatable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orders_order_id", nullable=false, insertable=false, updatable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


