// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2
package com.iti.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="naseejstore"
)
public class Orders  implements java.io.Serializable {


     private long orderId;
     private UserDetails userDetails;
     private String selectedAddress;
     private Date purchaseDate;
     private Set<OrdersHasProducts> ordersHasProductses = new HashSet<OrdersHasProducts>(0);

    public Orders() {
    }

	
    public Orders(long orderId, UserDetails userdetails, String selectedAddress, Date purchaseDate) {
        this.orderId = orderId;
        this.userDetails = userdetails;
        this.selectedAddress = selectedAddress;
        this.purchaseDate = purchaseDate;
    }
    public Orders(long orderId, UserDetails userdetails, String selectedAddress, Date purchaseDate, Set<OrdersHasProducts> ordersHasProductses) {
       this.orderId = orderId;
       this.userDetails = userdetails;
       this.selectedAddress = selectedAddress;
       this.purchaseDate = purchaseDate;
       this.ordersHasProductses = ordersHasProductses;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="order_id", unique=true, nullable=false)
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userdetails_id", nullable=false)
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userdetails) {
        this.userDetails = userdetails;
    }

    
    @Column(name="selected_address", nullable=false, length=100)
    public String getSelectedAddress() {
        return this.selectedAddress;
    }
    
    public void setSelectedAddress(String selectedAddress) {
        this.selectedAddress = selectedAddress;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="purchaseDate", nullable=false, length=10)
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<OrdersHasProducts> getOrdersHasProductses() {
        return this.ordersHasProductses;
    }
    
    public void setOrdersHasProductses(Set<OrdersHasProducts> ordersHasProductses) {
        this.ordersHasProductses = ordersHasProductses;
    }




}


