// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2
package com.iti.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="naseejstore"
)
public class OrderDetail implements java.io.Serializable {


    private long orderId;
    private UserDetails userDetails;
    private Date purchaseDate;
    private String selectedAddress;
    private Set<OrderHasProducts> orderHasProducts = new HashSet<OrderHasProducts>(0);

    public OrderDetail() {
    }


    public OrderDetail(UserDetails userDetails, Date purchaseDate, String selectedAddress) {
        this.userDetails = userDetails;
        this.purchaseDate = purchaseDate;
        this.selectedAddress = selectedAddress;
    }
    public OrderDetail(UserDetails userDetails, Date purchaseDate, String selectedAddress, Set<OrderHasProducts> orderHasProductses) {
        this.userDetails = userDetails;
        this.purchaseDate = purchaseDate;
        this.selectedAddress = selectedAddress;
        this.orderHasProducts = orderHasProductses;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="order_id", unique=true, nullable=false)
    public long getOrderId() {
        return this.orderId;
    }

    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userdetails_id", nullable=false)
    public UserDetails getUserDetails() {
        return this.userDetails;
    }

    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="purchaseDate", nullable=false, length=10)
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }

    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }


    @Column(name="selected_address", nullable=false, length=100)
    public String getSelectedAddress() {
        return this.selectedAddress;
    }

    public void setSelectedAddress(String selectedAddress) {
        this.selectedAddress = selectedAddress;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="orderDetails")
    public Set<OrderHasProducts> getOrderHasProducts() {
        return this.orderHasProducts;
    }

    public void setOrderHasProducts(Set<OrderHasProducts> orderHasProductses) {
        this.orderHasProducts = orderHasProductses;
    }




}