// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2
package com.iti.model.entity;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdersHasProductsId generated by hbm2java
 */
@Embeddable
public class OrdersHasProductsId  implements java.io.Serializable {


     private long ordersOrderId;
     private long productsProductId;

    public OrdersHasProductsId() {
    }

    public OrdersHasProductsId(long ordersOrderId, long productsProductId) {
       this.ordersOrderId = ordersOrderId;
       this.productsProductId = productsProductId;
    }
   


    @Column(name="orders_order_id", nullable=false)
    public long getOrdersOrderId() {
        return this.ordersOrderId;
    }
    
    public void setOrdersOrderId(long ordersOrderId) {
        this.ordersOrderId = ordersOrderId;
    }


    @Column(name="products_product_id", nullable=false)
    public long getProductsProductId() {
        return this.productsProductId;
    }
    
    public void setProductsProductId(long productsProductId) {
        this.productsProductId = productsProductId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdersHasProductsId) ) return false;
		 OrdersHasProductsId castOther = ( OrdersHasProductsId ) other; 
         
		 return (this.getOrdersOrderId()==castOther.getOrdersOrderId())
 && (this.getProductsProductId()==castOther.getProductsProductId());
   }
   
   public int hashCode() {
         long result = 17;
         
         result = 37 * result + this.getOrdersOrderId();
         result = 37 * result + this.getProductsProductId();
         return (int) result;
   }   


}


