// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2
package com.iti.model.entity;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdersHasProducts generated by hbm2java
 */
@Entity
@Table(name="orders_has_products"
    ,catalog="naseejstore"
)
public class OrderHasProducts  implements java.io.Serializable {


    private OrderHasProductsId id;
    private Product product;
    private OrderDetail orderDetail;
    private int quantity;

    public OrderHasProducts() {
    }

    public OrderHasProducts(OrderHasProductsId id, Product product, OrderDetail orderDetail, int quantity) {
        this.id = id;
        this.product = product;
        this.orderDetail = orderDetail;
        this.quantity = quantity;
    }

    @EmbeddedId


    @AttributeOverrides( {
            @AttributeOverride(name="ordersOrderId", column=@Column(name="orders_order_id", nullable=false) ),
            @AttributeOverride(name="productsProductId", column=@Column(name="products_product_id", nullable=false) ) } )
    public OrderHasProductsId getId() {
        return this.id;
    }

    public void setId(OrderHasProductsId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="products_product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orders_order_id", nullable=false, insertable=false, updatable=false)
    public OrderDetail getOrderDetails() {
        return this.orderDetail;
    }

    public void setOrderDetails(OrderDetail orderDetail) {
        this.orderDetail = orderDetail;
    }


    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


