// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2
package com.iti.model.entity;


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="naseejstore"
)
public class Product  implements java.io.Serializable {


    private Integer productId;
    private String category;
    private String description;
    private String firstImg;
    private double price;
    private int quantity;
    private String secondImg;
    private String size;
    private String type;
    private Set<Cart> carts = new HashSet<Cart>(0);
    private Set<OrderHasProducts> orderHasProductses = new HashSet<OrderHasProducts>(0);

    public Product() {
    }


    public Product(String category, String firstImg, double price, int quantity, String size, String type) {
        this.category = category;
        this.firstImg = firstImg;
        this.price = price;
        this.quantity = quantity;
        this.size = size;
        this.type = type;
    }
    public Product(String category, String description, String firstImg, double price, int quantity, String secondImg, String size, String type, Set<Cart> carts, Set<OrderHasProducts> orderHasProductses) {
        this.category = category;
        this.description = description;
        this.firstImg = firstImg;
        this.price = price;
        this.quantity = quantity;
        this.secondImg = secondImg;
        this.size = size;
        this.type = type;
        this.carts = carts;
        this.orderHasProductses = orderHasProductses;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="product_id", unique=true, nullable=false)
    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }


    @Column(name="category", nullable=false, length=45)
    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }


    @Column(name="description", length=255)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name="first_img", nullable=false, length=45)
    public String getFirstImg() {
        return this.firstImg;
    }

    public void setFirstImg(String firstImg) {
        this.firstImg = firstImg;
    }


    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }


    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }


    @Column(name="second_img", length=45)
    public String getSecondImg() {
        return this.secondImg;
    }

    public void setSecondImg(String secondImg) {
        this.secondImg = secondImg;
    }


    @Column(name="size", nullable=false, length=45)
    public String getSize() {
        return this.size;
    }

    public void setSize(String size) {
        this.size = size;
    }


    @Column(name="type", nullable=false, length=60)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Cart> getCarts() {
        return this.carts;
    }

    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<OrderHasProducts> getOrderHasProductses() {
        return this.orderHasProductses;
    }

    public void setOrderHasProductses(Set<OrderHasProducts> orderHasProductses) {
        this.orderHasProductses = orderHasProductses;
    }




}


