// default package
// Generated Mar 27, 2021, 4:05:51 PM by Hibernate Tools 6.0.0.Alpha2

package com.iti.model.entity;

import jakarta.persistence.Column;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sizes generated by hbm2java
 */
@Entity
@Table(name = "sizes"
        , catalog = "naseejstore"
)
public class Sizes implements java.io.Serializable {


    private String sizeName;

    public Sizes() {
    }

    public Sizes(String sizeName) {
        this.sizeName = sizeName;
    }

    @Id


    @Column(name = "size_name", unique = true, nullable = false, length = 45)
    public String getSizeName() {
        return this.sizeName;
    }

    public void setSizeName(String sizeName) {
        this.sizeName = sizeName;
    }


}


