package com.iti.model.entity;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Userdetails generated by hbm2java
 */
@Entity
@Table(name = "user_details"
        , catalog = "naseejstore"
        , uniqueConstraints = @UniqueConstraint(columnNames = "email")
)
public class UserDetails implements java.io.Serializable {

    private long id;
    private Date birthday;
    private Double creditLimit;
    private String email;
    private String image;
    private String job;
    private String password;
    private String phoneNumber;
    private String role;
    private String userName;
    private Set<Address> addresses = new HashSet<Address>(0);
    private Set<Cart> carts = new HashSet<Cart>(0);
    private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
    private Set<Interest> interests = new HashSet<Interest>(0);
    public UserDetails() {
    }

    public UserDetails(String email, String password, String phoneNumber, String userName) {
        this.email = email;
        this.password = password;
        this.phoneNumber = phoneNumber;
        this.userName = userName;
    }


    public UserDetails(Date birthday, Double creditLimit, String email, String image, String job, String password, String phoneNumber, String role, String userName, Set<Address> addresses, Set<Cart> carts, Set<OrderDetail> orderDetails, Set<Interest> interests) {
        this.birthday = birthday;
        this.creditLimit = creditLimit;
        this.email = email;
        this.image = image;
        this.job = job;
        this.password = password;
        this.phoneNumber = phoneNumber;
        this.role = role;
        this.userName = userName;
        this.addresses = addresses;
        this.carts = carts;
        this.orderDetails = orderDetails;
        this.interests = interests;
    }

    @Override
    public String toString() {
        return "UserDetails{" +
                "id=" + id +
                ", birthday=" + birthday +
                ", creditLimit=" + creditLimit +
                ", email='" + email + '\'' +
                ", image='" + image + '\'' +
                ", job='" + job + '\'' +
                ", password='" + password + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", role='" + role + '\'' +
                ", userName='" + userName + '\'' +
                ", addresses=" + addresses +
                ", interests=" + interests +
                '}';
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "birthday", length = 10)
    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }


    @Column(name = "credit_limit", precision = 22, scale = 0)
    public Double getCreditLimit() {
        return this.creditLimit;
    }

    public void setCreditLimit(Double creditLimit) {
        this.creditLimit = creditLimit;
    }


    @Column(name = "email", unique = true, nullable = false, length = 60)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name = "image", length = 45)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }


    @Column(name = "job", length = 45)
    public String getJob() {
        return this.job;
    }

    public void setJob(String job) {
        this.job = job;
    }


    @Column(name = "password", nullable = false, length = 45)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    @Column(name = "phone_number", nullable = false, length = 45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }


    @Column(name = "role", nullable = false, length = 45)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }


    @Column(name = "user_name", nullable = false, length = 60)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
    public Set<Address> getAddresses() {
        return this.addresses;
    }

    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
    public Set<Cart> getCarts() {
        return this.carts;
    }

    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }

    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userDetails")
    public Set<Interest> getInterests() {
        return this.interests;
    }

    public void setInterests(Set<Interest> interests) {
        this.interests = interests;
    }


}


