

package com.iti.model.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Userdetails generated by hbm2java
 */
@Entity
@Table(name="userdetails"
    ,catalog="naseejstore"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class UserDetails implements java.io.Serializable {


     private long id;
     private String email;
     private String userName;
     private String phoneNumber;
     private double creditLimit;
     private String image;
     private String role;
     private String job;
     private String password;
     private Date birthday;
     private Set<Interests> interestses = new HashSet<Interests>(0);
     private Set<Orders> orderses = new HashSet<Orders>(0);
     private Set<Address> addresses = new HashSet<Address>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);

    public UserDetails() {
    }

	
    public UserDetails(long id, String email, String userName, String phoneNumber) {
        this.id = id;
        this.email = email;
        this.userName = userName;
        this.phoneNumber = phoneNumber;
    }
    public UserDetails(long id, String email, String userName, String phoneNumber, double creditLimit, String image, String role, String job, String password, Date birthday, Set<Interests> interestses, Set<Orders> orderses, Set<Address> addresses, Set<Cart> carts) {
       this.id = id;
       this.email = email;
       this.userName = userName;
       this.phoneNumber = phoneNumber;
       this.creditLimit = creditLimit;
       this.image = image;
       this.role = role;
       this.job = job;
       this.password = password;
       this.birthday = birthday;
       this.interestses = interestses;
       this.orderses = orderses;
       this.addresses = addresses;
       this.carts = carts;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="email", unique=true, nullable=false, length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="user_name", nullable=false, length=60)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="phone_number", nullable=false, length=45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="credit_limit", precision=10, scale=3)
    public double getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(double creditLimit) {
        this.creditLimit = creditLimit;
    }

    
    @Column(name="image", length=45)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="role", length=45)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="job", length=45)
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", length=10)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userDetails")
    public Set<Interests> getInterestses() {
        return this.interestses;
    }
    
    public void setInterestses(Set<Interests> interestses) {
        this.interestses = interestses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userDetails")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }


    @OneToMany(fetch=FetchType.LAZY, mappedBy="userDetails")
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userDetails")
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }




}


